version: "3"

services:
  gateway:
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - ui

  api:
    image: node:alpine
    container_name: expense-tracker-api
    working_dir: /usr/expense-tracker/api
    ports:
      - 5000:5000
    environment:
      SERVER_PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: expense-tracker
      DB_USERNAME: root
      DB_PASSWORD: admin
    volumes:
      - ./api:/usr/expense-tracker/api
    command: sh -c "npm install && npm run start"

  ui:
    image: node:alpine
    container_name: expense-tracker-ui
    working_dir: /usr/expense-tracker/ui
    ports:
      - 3000:3000
    volumes:
      - ./ui:/usr/expense-tracker/ui
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_DB: expense-tracker
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    container_name: expense-tracker-db
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: expense-tracker-pgadmin
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: arkey99700@gmail.com
      PGADMIN_DEFAULT_PASSWORD: a25102019
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - db
